In [181]:
import numpy as np
import pandas as pd
baftas = pd.read_csv('baftas.csv')

In [182]:
nominee = pd.Series(baftas.nominee.unique())
workers = pd.Series(baftas.workers.unique())
names = nominee.append(workers)
names = pd.Series(names.unique())

In [183]:
def bafta_noms(name):
    nom = baftas.query('nominee == @name | workers == @name').year.values
    won = baftas.query('(nominee == @name | workers == @name) & winner == True').year.values
    return dict(nom=nom, won=won)

In [214]:
df = pd.DataFrame(columns=['nom', 'won'])


In [221]:
for name in names:
    res = bafta_noms(name)
    ser = pd.Series(res, name=name)
    df = df.append(ser)


In [233]:
df


nom     won
The Fallen Idol                                           [1949, 1949]  [1949]
Hamlet                                              [1949, 1949, 1992]  [1949]
Oliver Twist                                                    [1949]      []
The Fallen Idol                                           [1949, 1949]  [1949]
Hamlet                                              [1949, 1949, 1992]  [1949]
...                                                                ...     ...
Ivan Busquets, Leandro Estebecorena, Stephane G...              [2020]      []
Andrew R. Jones, Robert Legato, Elliot Newman, ...              [2020]      []
Roger Guyett, Paul Kavanagh, Neal Scanlan, Domi...              [2020]      []
A Beautiful Day in the Neighborhood                             [2020]      []
Laura Dern                                                      [2020]  [2020]

[4479 rows x 2 columns]

In [234]:
df.to_csv('bafta_noms_years.csv')

In [243]:
globes = pd.read_csv('globes_.csv')

In [237]:
nominee = pd.Series(globes.nominee.unique())
film = pd.Series(globes.film.unique())
names = nominee.append(film)
names = pd.Series(names.unique())

In [244]:
def globes_noms(name):
    nom = globes.query('nominee == @name | film == @name').year_award.values
    won = globes.query('(nominee == @name | film == @name) & win == True').year_award.values
    return dict(nom=nom, won=won)

In [245]:
df = pd.DataFrame(columns=['nom', 'won'])

In [246]:
for name in names:
    res = globes_noms(name)
    ser = pd.Series(res, name=name)
    df = df.append(ser)

In [247]:
df

nom                 won
Katina Paxinou                                    [1944]              [1944]
Akim Tamiroff                                     [1944]              [1944]
Henry King                                  [1944, 1956]        [1944, 1956]
The Song Of Bernadette                [1944, 1944, 1944]  [1944, 1944, 1944]
Jennifer Jones                              [1944, 1975]              [1944]
...                                                  ...                 ...
On Becoming a God in Central Florida              [2020]                  []
Russian Doll                                      [2020]                  []
Ramy                                              [2020]              [2020]
The Politician                                    [2020]                  []
Living with Yourself                              [2020]                  []

[6441 rows x 2 columns]

In [248]:
df.to_csv('globes_noms_year.csv')

In [295]:
oscars = pd.read_csv('the_oscar_award.csv')

In [296]:
nominee = pd.Series(oscars.name.unique())
film = pd.Series(oscars.film.unique())
names = nominee.append(film)
names = pd.Series(names.unique())

In [297]:
def oscars_noms(name):
    nom = oscars.query('name == @name | film == @name').year_ceremony.values
    won = oscars.query('(name == @name | film == @name) & winner == True').year_ceremony.values
    return dict(nom=nom, won=won)

In [298]:
df = pd.DataFrame(columns=['nom', 'won'])

In [299]:
for name in names:
    res = oscars_noms(name)
    ser = pd.Series(res, name=name)
    df = df.append(ser)

In [343]:
df

nom     won
Richard Barthelmess              [1928]      []
Emil Jannings                    [1928]  [1928]
Louise Dresser                   [1928]      []
Janet Gaynor               [1928, 1938]  [1928]
Gloria Swanson       [1928, 1930, 1951]      []
...                                 ...     ...
Saria                            [2020]      []
A Sister                         [2020]      []
Ad Astra                         [2020]      []
Avengers: Endgame                [2020]      []
Knives Out                       [2020]      []

[11493 rows x 2 columns]

In [344]:
df.to_csv('oscar_noms_by_year.csv')

In [361]:
df.filter(like='Billy Wilder', axis=0).nom.values #to find names in team awards


array([array([1940]), array([1942]), array([1942, 1946]),
       array([1945, 1946, 1951, 1954, 1955, 1958, 1960, 1961, 1988]),
       array([1945]), array([1949]), array([1951]), array([1952]),
       array([1955]), array([1960, 1961, 1967]), array([1961])],
      dtype=object)